import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        primary: '#00639a',
        'on-primary': '#ffffff',
        'primary-container': '#5da9e9',
        'primary-fixed': '#cee5ff',
        'primary-fixed-dim': '#96ccff',
        'on-primary-fixed': '#001d32',
        'on-primary-fixed-variant': '#004a76',
        'on-primary-container': '#003c61',
        'inverse-primary': '#96ccff',
        secondary: '#845400',
        'on-secondary': '#ffffff',
        'secondary-container': '#feb246',
        'secondary-fixed': '#ffddb6',
        'secondary-fixed-dim': '#ffb95a',
        'on-secondary-fixed': '#2a1800',
        'on-secondary-fixed-variant': '#643f00',
        'on-secondary-container': '#6f4600',
        tertiary: '#006d41',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#55b57f',
        'tertiary-fixed': '#95f7bb',
        'tertiary-fixed-dim': '#7adaa1',
        'on-tertiary-fixed': '#002110',
        'on-tertiary-fixed-variant': '#005230',
        'on-tertiary-container': '#004326',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#f8f9ff',
        'on-background': '#0b1c30',
        surface: '#f8f9ff',
        'on-surface': '#0b1c30',
        'surface-variant': '#d3e4fe',
        'on-surface-variant': '#404750',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'surface-tint': '#00639a',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        outline: '#707881',
        'outline-variant': '#c0c7d1',
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      fontFamily: {
        sans: ['var(--font-plus-jakarta-sans)', 'system-ui', 'sans-serif'],
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        md: '24px',
        lg: '40px',
        xl: '64px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
export default config
