import { BankHoliday } from './interface/bankHolidays'

export const bankHolidays: Record<string, BankHoliday[]> = {
  '2024': [
    {
      date: '2024-01-01',
      description: "Jour de l'an",
      emoji: '🔄',
      link: 'blog/pourquoi-le-1er-janvier-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2024-04-01',
      description: 'Lundi de Pâques',
      emoji: '🐰',
      link: 'blog/pourquoi-le-lundi-de-paques-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2024-05-01',
      description: 'Fête du travail',
      emoji: '🌴',
      link: 'blog/pourquoi-le-1er-mai-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2024-05-08',
      description: 'Victoire 1945',
      emoji: '🪖',
      link: 'blog/pourquoi-le-8-mai-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2024-05-09',
      description: 'Ascension',
      emoji: '☁️',
      link: 'blog/pourquoi-l-ascension-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2024-05-19',
      description: 'Pentecôte',
      emoji: '😇',
      link: 'blog/pourquoi-la-pentecote-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2024-07-14',
      description: 'Fête nationale',
      emoji: '🇫🇷',
      link: 'blog/pourquoi-le-14-juillet-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2024-08-15',
      description: 'Assomption',
      emoji: '👩🏼',
      link: 'blog/pourquoi-le-15-aout-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2024-11-01',
      description: 'Toussaint',
      emoji: '💀',
      link: 'blog/pourquoi-le-1er-novembre-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2024-11-11',
      description: 'Armistice 1918',
      emoji: '✌🏼',
      link: 'blog/pourquoi-le-11-novembre-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2024-12-25',
      description: 'Jour de Noël',
      emoji: '🌲',
      link: 'blog/pourquoi-le-25-decembre-est-ferie',
      image: '/1er-mai.png',
    },
  ],
  '2025': [
    {
      date: '2025-01-01',
      description: "Jour de l'an",
      emoji: '🔄',
      link: 'blog/pourquoi-le-1er-janvier-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2025-04-21',
      description: 'Lundi de Pâques',
      emoji: '🐰',
      link: 'blog/pourquoi-le-lundi-de-paques-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2025-05-01',
      description: 'Fête du travail',
      emoji: '🌴',
      link: 'blog/pourquoi-le-1er-mai-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2025-05-08',
      description: 'Victoire 1945',
      emoji: '🪖',
      link: 'blog/pourquoi-le-8-mai-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2025-05-29',
      description: 'Ascension',
      emoji: '☁️',
      link: 'blog/pourquoi-l-ascension-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2025-06-08',
      description: 'Pentecôte',
      emoji: '😇',
      link: 'blog/pourquoi-la-pentecote-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2025-07-14',
      description: 'Fête nationale',
      emoji: '🇫🇷',
      link: 'blog/pourquoi-le-14-juillet-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2025-08-15',
      description: 'Assomption',
      emoji: '👩🏼',
      link: 'blog/pourquoi-le-15-aout-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2025-11-01',
      description: 'Toussaint',
      emoji: '💀',
      link: 'blog/pourquoi-le-1er-novembre-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2025-11-11',
      description: 'Armistice 1918',
      emoji: '✌🏼',
      link: 'blog/pourquoi-le-11-novembre-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2025-12-25',
      description: 'Jour de Noël',
      emoji: '🎄',
      link: 'blog/pourquoi-le-25-decembre-est-ferie',
      image: '/1er-mai.png',
    },
  ],
  '2026': [
    {
      date: '2026-01-01',
      description: "Jour de l'an",
      emoji: '🔄',
      link: 'blog/pourquoi-le-1er-janvier-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2026-04-06',
      description: 'Lundi de Pâques',
      emoji: '🐰',
      link: 'blog/pourquoi-le-lundi-de-paques-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2026-05-01',
      description: 'Fête du travail',
      emoji: '🌴',
      link: 'blog/pourquoi-le-1er-mai-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2026-05-08',
      description: 'Victoire 1945',
      emoji: '🪖',
      link: 'blog/pourquoi-le-8-mai-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2026-05-14',
      description: 'Ascension',
      emoji: '☁️',
      link: 'blog/pourquoi-l-ascension-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2026-05-24',
      description: 'Pentecôte',
      emoji: '😇',
      link: 'blog/pourquoi-la-pentecote-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2026-07-14',
      description: 'Fête nationale',
      emoji: '🇫🇷',
      link: 'blog/pourquoi-le-14-juillet-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2026-08-15',
      description: 'Assomption',
      emoji: '👩🏼',
      link: 'blog/pourquoi-le-15-aout-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2026-11-01',
      description: 'Toussaint',
      emoji: '💀',
      link: 'blog/pourquoi-le-1er-novembre-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2026-11-11',
      description: 'Armistice 1918',
      emoji: '✌🏼',
      link: 'blog/pourquoi-le-11-novembre-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2026-12-25',
      description: 'Jour de Noël',
      emoji: '🌲',
      link: 'blog/pourquoi-le-25-decembre-est-ferie',
      image: '/1er-mai.png',
    },
  ],
  '2027': [
    {
      date: '2027-01-01',
      description: "Jour de l'an",
      emoji: '🔄',
      link: 'blog/pourquoi-le-1er-janvier-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2027-03-29',
      description: 'Lundi de Pâques',
      emoji: '🐰',
      link: 'blog/pourquoi-le-lundi-de-paques-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2027-05-01',
      description: 'Fête du travail',
      emoji: '🌴',
      link: 'blog/pourquoi-le-1er-mai-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2027-05-08',
      description: 'Victoire 1945',
      emoji: '🪖',
      link: 'blog/pourquoi-le-8-mai-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2027-05-06',
      description: 'Ascension',
      emoji: '☁️',
      link: 'blog/pourquoi-l-ascension-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2027-05-16',
      description: 'Pentecôte',
      emoji: '😇',
      link: 'blog/pourquoi-la-pentecote-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2027-07-14',
      description: 'Fête nationale',
      emoji: '🇫🇷',
      link: 'blog/pourquoi-le-14-juillet-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2027-08-15',
      description: 'Assomption',
      emoji: '👩🏼',
      link: 'blog/pourquoi-le-15-aout-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2027-11-01',
      description: 'Toussaint',
      emoji: '💀',
      link: 'blog/pourquoi-le-1er-novembre-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2027-11-11',
      description: 'Armistice 1918',
      emoji: '✌🏼',
      link: 'blog/pourquoi-le-11-novembre-est-ferie',
      image: '/1er-mai.png',
    },
    {
      date: '2027-12-25',
      description: 'Jour de Noël',
      emoji: '🌲',
      link: 'blog/pourquoi-le-25-decembre-est-ferie',
      image: '/1er-mai.png',
    },
  ],
}
